<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Deepshri_laptop" failures="1" tests="8" name="api.tests.GitCRUDTests" time="5.215" errors="0" timestamp="2024-03-21T09:52:51 CDT" skipped="0">
  <testcase classname="api.tests.GitCRUDTests" name="test_GetAllRepo" time="2.367"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_createRepo" time="1.270"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_singleRepo" time="0.283"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_createRepowithExistingName" time="0.278"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_DeleteRepoByName" time="0.394"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_DeleteRepoByNonexistingName" time="0.238"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_singleRepowithNonExistingRepoName" time="0.185"/>
  <system-out/>
  <testcase classname="api.tests.GitCRUDTests" name="test_UpdateRepoName" time="0.200">
    <failure message="expected:&lt;307&gt; but was:&lt;200&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<307> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:213)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:218)
at api.tests.GitCRUDTests.test_UpdateRepoName(GitCRUDTests.java:140)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_UpdateRepoName -->
  <system-out/>
</testsuite> <!-- api.tests.GitCRUDTests -->
